Repository belighted/bosa, pull requests merged in 2021-06, with the labels that each got.

#74 fake personal data and remove identities & encrypted data
  lib/tasks/users.rake
Labels: code review required, squash commits required

#76 BOSA21Q1-320 Verify CSAM data are always saved
  Gemfile.lock
  db/migrate/20210601100007_add_decidim_verifications_omniauth_encrypted_metadata_to_authorizations.decidim_verifications_omniauth.rb
  db/migrate/20210601100008_allow_null_email_in_decidim_users.decidim_verifications_omniauth.rb
  db/schema.rb
Labels: code review required

#80 Fix metadata read issue in verifications_omniauth module
  Gemfile.lock
Labels: code review required, ready to merge

#81 BOSA21Q1-320 Fix updating authorization metadata and encryption
  Gemfile.lock
Labels: code review required, ready to merge

#83 BOSA21Q1-335, BOSA21Q1-334 Cookies module shouldn't register itself as a component
  Gemfile.lock
Labels: code review required, ready to merge

#91 BOSA21Q1-16 Front office: in the conversation module > delete the limitation of characters in a conversation
  lib/extends/decidim-core/app/models/decidim/messaging/message.rb
Labels: code review required

#92 BOSA21Q1-200 Drawing: error in display on result page
  Gemfile.lock
Labels: code review required

#96 BOSA21Q1-355 De Kamer: add e-mail in authorization data in back office
  app/views/decidim/verifications/metadata/_content.html.erb
Labels: code review required, ready to merge

#100 BOSA21Q1-359 Fix voting process is lasting too long
  Gemfile.lock
Labels: code review required, ready to merge

#95 BOSA21Q1-94 Min signatures per region is attended, send notification and e-mail
  app/events/decidim/initiatives/admin/support_threshold_reached_for_scope_event.rb
  app/events/decidim/initiatives/support_threshold_reached_for_scope_event.rb
  app/models/decidim/initiative.rb
  config/locales/decidim-initiatives/en.yml
  config/locales/decidim-initiatives/fr.yml
  config/locales/decidim-initiatives/nl.yml
  lib/extends/decidim-initiatives/app/commands/decidim/initiatives/vote_initiative.rb
Labels: code review required, ready to merge, squash commits required

#94 BOSA21Q1-170 Bosa & Bosa cities: hide proposals in presentation page of a process
  app/views/decidim/participatory_processes/participatory_processes/show.html.erb
Labels: code review required

#88 BOSA21Q1-210 admin panel: add a table in wysiwyg
  app/assets/javascripts/decidim/admin/editor.js.es6
  app/assets/javascripts/decidim/admin/quill-2.0.0-dev.3.min.js
  app/assets/javascripts/decidim/admin/quill-better-table-plugin.min.js
  app/assets/javascripts/decidim/admin/quill_iframe_plugin.js
  app/assets/stylesheets/decidim.scss
  app/assets/stylesheets/decidim/quill-plugins/2.0.0-dev.3-quill.snow.min.css
  app/assets/stylesheets/decidim/quill-plugins/quill-better-table-plugin.css
  app/assets/stylesheets/decidim_admin_extends.scss
  app/views/decidim/initiatives/admin/initiatives/_form.html.erb
  app/views/decidim/initiatives/initiatives/show.html.erb
  app/views/decidim/suggestions/admin/suggestions/_form.html.erb
Labels: Do Not Merge, code review required

#103 BOSA21Q1-387 On a suggestion page, make the name of the author clickable to see his public profile (as on initiative)
  Gemfile.lock
Labels: code review required

#85 BOSA21Q1-181 BOSA + BOSA cities: add translations
  lib/extends/decidim-core/app/controllers/decidim/devise/sessions_controller.rb
Labels: code review required

#105 BOSA21Q1-396 Issue sharing the petition on FB, wrong preview title
  app/views/layouts/decidim/_head.html.erb
Labels: code review required, ready to merge

#106 BOSA21Q1-396 Issue sharing the petition on FB - fix title displayed twice
  app/views/decidim/initiatives/initiatives/show.html.erb
Labels: code review required, ready to merge

#107 BOSA21Q1-341: recover translation option for comments
  Gemfile
  Gemfile.lock
  app/assets/javascripts/decidim/translations.js.es6
  app/cells/decidim/comments/comment/show.erb
  lib/extends/decidim-comments/lib/decidim/comments/comments_helper.rb
Labels: code review required, ready to merge

#109 BOSA21Q1-131 & BOSA21Q1-356 democratie.brussels : signature gauge in several parts
  app/cells/decidim/progress_bar/show.erb
  app/models/decidim/initiative.rb
  app/views/decidim/initiatives/admin/initiatives/_form.html.erb
  app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
  config/locales/decidim-initiatives/en.yml
  config/locales/decidim-initiatives/fr.yml
  config/locales/decidim-initiatives/nl.yml
  lib/extends/decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_form.rb
Labels: code review required, ready to merge

#110 BOSA21Q1-396 Remove the cache of js and css files
  app/views/layouts/decidim/_head.html.erb
Labels: code review required, ready to merge

#104 BOSA21Q1-386: add fragment caching for initiative#show view
  app/views/decidim/initiatives/initiatives/_author.html.erb
  app/views/decidim/initiatives/initiatives/_tags.html.erb
  app/views/decidim/initiatives/initiatives/show.html.erb
Labels: code review required, ready to merge

#97 BOSA21Q1-96: migrate test suite to 0.24 version
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/uploaders/decidim/area_logo_uploader.rb
  lib/decidim/core/test/factories.rb
  lib/extends/decidim-admin/app/forms/decidim/admin/area_form.rb
  lib/extends/decidim-core/app/models/decidim/area.rb
  lib/extends/decidim-generators/lib/decidim/generators/app_templates/dummy_authorization_handler.rb
  spec/decidim-admin/spec/system/admin_manages_organization_areas_spec.rb
  spec/decidim-core/spec/lib/exporters/csv_spec.rb
  spec/decidim-core/spec/lib/exporters/excel_spec.rb
  spec/decidim-initiatives/spec/forms/admin/initiative_type_form_spec.rb
  spec/decidim-initiatives/spec/forms/initiative_form_spec.rb
  spec/decidim-initiatives/spec/shared/create_initiative_type_example.rb
  spec/decidim-initiatives/spec/shared/update_initiative_type_example.rb
  spec/decidim-verifications/spec/services/decidim/dummy_authorization_handler_spec.rb
  spec/decidim-verifications/spec/system/authorizations_spec.rb
  spec/spec_helper.rb
  spec/support/cuprite_setup.rb
Labels: code review required, ready to merge

#98 BOSA21Q1-19 nickname rules?
  app/views/decidim/account/show.html.erb
  app/views/decidim/devise/registrations/new.html.erb
  config/locales/decidim-core/en.yml
  config/locales/decidim-core/fr.yml
  config/locales/decidim-core/nl.yml
Labels: code review required, squash commits required

#108 BOSA21Q1-144 Suggestions/inititatives: notification when signature deadline is over
  Gemfile.lock
  app/events/decidim/initiatives/admin/support_period_finished_event.rb
  app/events/decidim/initiatives/support_period_finished_event.rb
  app/jobs/check_published_suggestions.rb
  app/jobs/check_validating_suggestions.rb
  app/jobs/notify_progress_suggestions.rb
  config/locales/decidim-initiatives/en.yml
  config/locales/decidim-initiatives/fr.yml
  config/locales/decidim-initiatives/nl.yml
  config/sidekiq.yml
  lib/tasks/decidim_initiatives_extras.rake
Labels: ready to merge, squash commits required

#112 BOSA21Q1-408: add appsignal integration for puma
  config/initializers/appsignal.rb
  config/puma.rb
Labels: ready to merge

#113 BOSA21Q1-389 translation "see other versions" in petition/suggestion …
  config/locales/decidim-initiatives/nl.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/nl.yml
Labels: code review required, ready to merge

#114 BOSA21Q1-144 Fix check_published_suggestions job
  app/jobs/check_published_suggestions.rb
Labels: code review required, ready to merge

#115 BOSA21Q1-357: fix displaying list with links
  app/assets/stylesheets/decidim/extends/_external-link.scss
Labels: ready to merge

#116 BOSA21Q1-356 Digital and paper signatures - fix displaying colors
  app/assets/stylesheets/decidim/extends/_progress-bar.scss
  app/models/decidim/initiative.rb
  app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
  lib/extends/decidim-core/app/cells/decidim/progress_bar_cell.rb
Labels: code review required, ready to merge

#117 BOSA21Q1-356 Digital and paper signatures
  app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
Labels: code review required, ready to merge

#119 BOSA21Q1-393: fix issue with displaying links in the footer
  app/views/layouts/decidim/_wrapper.html.erb
Labels: ready to merge

#121 BOSA21Q1-131 Fix signature gauge display for online+offline and single scope
  app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
  config/locales/decidim-initiatives/en.yml
  config/locales/decidim-initiatives/fr.yml
  config/locales/decidim-initiatives/nl.yml
Labels: ready to merge

#122 BOSA21Q1-415 Ensure files generated by sidekiq are saved on minio (S3)
  config/sidekiq.yml
Labels: ready to merge

#123 BOSA21Q1-417 Ingelmunster: confirmation email user not as usual
  config/locales/nl.yml
Labels: ready to merge

#124 BOSA21Q1-415 Enable schedule tab in sidekiq-web
  config/initializers/sidekiq.rb
Labels: ready to merge

#125 BOSA21Q1-412 Preventing XSS in user name
  lib/extends/decidim-core/app/presenters/decidim/user_presenter.rb
Labels: ready to merge
